### ISSUE TITLE
Retrieving Quote with Product Details fails

### ISSUE THREAD

**Issue by gbillyb** [A2Z-Cloud/Talk-Zoho#11]
Using the following command:
`quote=wait(crm.quotes.get,'2359829000000265119')`
results in this error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/talkzoho/crm/utils.py", line 57, in unwrap_items
    return [translate_item(i) for i in items]
  File "/usr/local/lib/python3.5/site-packages/talkzoho/crm/utils.py", line 57, in <listcomp>
    return [translate_item(i) for i in items]
  File "/usr/local/lib/python3.5/site-packages/talkzoho/crm/utils.py", line 118, in translate_item
    return {kwarg['val']: nullify(kwarg['content']) for kwarg in fields}
  File "/usr/local/lib/python3.5/site-packages/talkzoho/crm/utils.py", line 118, in <dictcomp>
    return {kwarg['val']: nullify(kwarg['content']) for kwarg in fields}
KeyError: 'content'`

Using CURL to retrieve the Quote (most of the detail has been omitted to help with readability):
`{
  "response": {
    "result": {
      "Quotes": {
        "row": {
          "no": "1",
          "FL": [
            {
              "val": "QUOTEID",
              "content": "2359829000000265119"
            },
            {
              "val": "Quote Number",
              "content": "2359829000000265125"
            }
.
.
.
           {
              "val": "Product Details",
              "product": [
                {
                  "no": "1",
                  "FL": [
                    {
                      "val": "Product Id",
                      "content": "2359829000000256110"
                    },
                    {
                      "val": "ITEMLINEID",
                      "content": "2359829000000265141"
                    }
...
`

The Utils.py module is expecting a val:content dict but the Product detail has val:product instead.
I suspect this will be the same for Sales Orders and Invoices too.

**Comment by jamesstidard** [comment]
Thanks for the heads up @gbillyb. I just pushed a fix to this and should be on pypi now as `2.0.9`.

**Comment by gbillyb** [comment]
@jamesstidard Thanks for the fix, any chance of a fix for when inserting or updating Quotes/SalesOrders/Invoices?

e.g.: https://www.zoho.com/crm/help/api/insertrecords.html#Quotes
